language: julia

julia:
  - 1

codecov: true

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("CreditMetrics")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
        - julia -e 'using Pkg; cd(Pkg.dir("CreditMetrics.jl")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
